default:
    image: python:3.10
    before_script:
        - apt-get update
        - apt-get install -y python3-pip
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install .

stages:
    - test
    - build
    - deploy
    - dummy


test:
    script:
        - coverage run -m unittest discover -s tests/unit
        - coverage report

release-prod-internal:
  stage: deploy
  environment: production
  script:
    - echo "This job deploys from the $CI_COMMIT_BRANCH branch to the package repository of gitlab.lrz.de."
    - python -m pip install build
    - python -m pip install twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
     
dummy:
    script:
        - echo "Pipeline finished"
